aiq:
  apps:
    backend:
      imagePullSecrets:
        - name: ngc-secret
      deploymentStrategy:
        type: Recreate
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          cpu: "2"
          memory: 3Gi
      env:
        DASK_NTHREADS: "2"
    frontend:
      imagePullSecrets:
        - name: ngc-secret
      service:
        port: 3000
        targetPort: 3000
    postgres:
      imagePullSecrets: 
        - name: ngc-secret
