aiq:
  apps:
    backend:
      imagePullSecrets:
        - name: ngc-secret
    frontend:
      imagePullSecrets:
        - name: ngc-secret
      service:
        port: 3000
        targetPort: 3000
    postgres:
      imagePullSecrets: 
        - name: ngc-secret
