#!/usr/bin/env bash
# =============================================================================
# AIQ-on-Kubernetes launchable - single-VM bring-up.
#
# This is the entrypoint the Brev Launchable runs. On one Ubuntu VM it:
#   1. installs Ansible and host dependencies
#   2. generates a localhost inventory
#   3. renders launchable overrides from .env
#   4. runs the Ansible playbook to install k3s and Helm
#
# Re-runnable: Ansible tasks are idempotent. Use ANSIBLE_TAGS to run a subset,
# for example: ANSIBLE_TAGS=k3s ./scripts/setup.sh
# =============================================================================
set -euo pipefail

# ---- paths ------------------------------------------------------------------
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
ANSIBLE_DIR="$ROOT/ansible"

# ---- logging ----------------------------------------------------------------
log()  { printf '\033[1;32m[+]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[!]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[x]\033[0m %s\n' "$*" >&2; exit 1; }
yaml_quote() {
  local value="${1//\'/\'\'}"
  printf "'%s'" "$value"
}

# ---- sudo -------------------------------------------------------------------
SUDO=""
if [[ "$(id -u)" -ne 0 ]]; then
  command -v sudo >/dev/null 2>&1 || die "Need root or sudo to install packages and k3s."
  SUDO="sudo"
fi

# ---- load .env --------------------------------------------------------------
if [[ -f "$ROOT/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "$ROOT/.env"
  set +a
  log "Loaded $ROOT/.env"
else
  warn "No .env found. Continuing with defaults; copy .env.example to .env for local overrides."
fi

# ---- config (env or defaults) ----------------------------------------------
K3S_CHANNEL="${K3S_CHANNEL:-v1.34}"
K3S_VERSION="${K3S_VERSION:-}"
INSTALL_K3S="${INSTALL_K3S:-true}"
INSTALL_HELM="${INSTALL_HELM:-true}"
ENABLE_WORKSHOP="${ENABLE_WORKSHOP:-false}"
WORKSHOP_PORT="${WORKSHOP_PORT:-3000}"

# ---- preflight --------------------------------------------------------------
log "Preflight checks"
[[ -r /etc/os-release ]] && . /etc/os-release || true
[[ "${ID:-}" == "ubuntu" || "${ID_LIKE:-}" == *debian* ]] || \
  warn "This launchable targets Ubuntu/Debian; '${ID:-unknown}' may need manual tweaks."

cores="$(nproc 2>/dev/null || echo '?')"
memgb="$(awk '/MemTotal/ {printf "%.0f", $2/1024/1024}' /proc/meminfo 2>/dev/null || echo '?')"
log "Host: ${cores} vCPU, ${memgb} GB RAM, arch $(uname -m)"

# ---- host deps: Ansible -----------------------------------------------------
if ! command -v ansible-playbook >/dev/null 2>&1; then
  log "Installing Ansible and base packages"
  export DEBIAN_FRONTEND=noninteractive
  $SUDO apt-get update -y
  $SUDO apt-get install -y ansible python3 python3-pip curl git ca-certificates gnupg lsb-release \
    || { warn "apt install of ansible failed; trying pip"; $SUDO python3 -m pip install --upgrade ansible-core; }
else
  log "Ansible already present: $(ansible-playbook --version | head -1)"
fi

# ---- generate inventory (localhost, no SSH) --------------------------------
log "Writing single-node localhost inventory"
mkdir -p "$ANSIBLE_DIR/inventory/group_vars"
cat > "$ANSIBLE_DIR/inventory/hosts.ini" <<'EOF'
# Generated by scripts/setup.sh - single-node, local connection.
[server]
localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python3

[agents]

[k3s_cluster:children]
server
agents
EOF

# ---- generate launchable overrides -----------------------------------------
SECRETS="$ANSIBLE_DIR/inventory/group_vars/secrets.yml"
log "Rendering $SECRETS from .env"
cat > "$SECRETS" <<EOF
# Generated by scripts/setup.sh from .env. Do not commit.
k3s_channel: $(yaml_quote "$K3S_CHANNEL")
k3s_version: $(yaml_quote "$K3S_VERSION")
install_k3s: ${INSTALL_K3S}
install_helm: ${INSTALL_HELM}
EOF
chmod 600 "$SECRETS"

# ---- run the playbook -------------------------------------------------------
log "Running Ansible playbook"
TAGS_ARG=()
[[ -n "${ANSIBLE_TAGS:-}" ]] && TAGS_ARG=(--tags "$ANSIBLE_TAGS")

(
  cd "$ANSIBLE_DIR"
  ansible-playbook site.yml \
    -e @inventory/group_vars/secrets.yml \
    "${TAGS_ARG[@]}"
) || die "Ansible run failed. Fix the error above and re-run ./scripts/setup.sh"

# ---- teaching website (optional) -------------------------------------------
deploy_workshop() {
  local web="$ROOT/web"
  [[ -d "$web" ]] || { warn "web/ not present; skipping teaching site."; return 0; }

  if ! command -v node >/dev/null 2>&1 || [[ "$(node -v 2>/dev/null | sed 's/v\([0-9]*\).*/\1/')" -lt 20 ]]; then
    log "Installing Node.js 20 and build tools for the teaching site"
    curl -fsSL https://deb.nodesource.com/setup_20.x | $SUDO -E bash -
    $SUDO apt-get install -y nodejs build-essential python3
  fi

  log "Building the teaching site"
  ( cd "$web" && npm install --include=dev --no-fund --no-audit && npm run build )

  log "Installing aiq-k8s-workshop systemd service on port ${WORKSHOP_PORT}"
  local run_user
  run_user="$(id -un)"
  $SUDO tee /etc/systemd/system/aiq-k8s-workshop.service >/dev/null <<EOF
[Unit]
Description=AIQ on Kubernetes teaching site
After=network-online.target k3s.service
Wants=network-online.target

[Service]
Type=simple
User=${run_user}
WorkingDirectory=${web}
Environment=NODE_ENV=production
Environment=PORT=${WORKSHOP_PORT}
Environment=HOST=0.0.0.0
Environment=KUBECONFIG=/etc/rancher/k3s/k3s.yaml
Environment=LAB_KUBECONFIG=/etc/rancher/k3s/k3s.yaml
Environment=LAB_CWD=${ROOT}
Environment=LAB_RC=${web}/lab/labrc
ExecStart=$(command -v node) ${web}/server.mjs
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
  $SUDO systemctl daemon-reload
  $SUDO systemctl enable aiq-k8s-workshop.service >/dev/null 2>&1 || true
  $SUDO systemctl restart aiq-k8s-workshop.service
  log "Teaching site running on port ${WORKSHOP_PORT}"
}

if [[ "${ENABLE_WORKSHOP}" == "true" ]]; then
  if [[ -n "${ANSIBLE_TAGS:-}" ]]; then
    log "ANSIBLE_TAGS=${ANSIBLE_TAGS} set; skipping teaching-site rebuild."
  else
    deploy_workshop || warn "Teaching site deploy failed. The Kubernetes setup is still complete."
  fi
fi

# ---- access summary ---------------------------------------------------------
KUBECONFIG_PATH="/etc/rancher/k3s/k3s.yaml"
NODE_IP="$(hostname -I 2>/dev/null | awk '{print $1}')"

cat <<EOF

$(log "Done. Kubernetes is running on this VM.")
  Cluster
    export KUBECONFIG=${KUBECONFIG_PATH}
    kubectl get nodes
    kubectl get pods -A

  Helm
    helm version

  AI-Q
    Not installed by setup. The tutorial will guide deployment with kubectl and Helm.

$( [[ "${ENABLE_WORKSHOP}" == "true" ]] && printf '  Teaching site\n    http://%s:%s/\n    expose port %s on Brev to open it from your browser\n\n' "${NODE_IP:-<vm-ip>}" "${WORKSHOP_PORT}" "${WORKSHOP_PORT}" )

  Re-run after editing .env:
    ./scripts/setup.sh

  Node IP:
    ${NODE_IP:-<vm-ip>}
EOF
