#!/usr/bin/env bash
# =============================================================================
# AIQ-on-Kubernetes launchable — single-VM bring-up.
#
# This is the entrypoint the Brev Launchable runs. On one Ubuntu VM it:
#   1. installs Ansible and host dependencies
#   2. generates a localhost inventory
#   3. renders launchable overrides from .env
#   4. runs the Ansible playbook to install k3s and Helm
#
# Re-runnable: Ansible tasks are idempotent. Use ANSIBLE_TAGS to run a subset,
# for example: ANSIBLE_TAGS=k3s ./scripts/setup.sh
# =============================================================================
set -euo pipefail

# ---- paths ------------------------------------------------------------------
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
ANSIBLE_DIR="$ROOT/ansible"

# ---- logging ----------------------------------------------------------------
log()  { printf '\033[1;32m[+]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[!]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[x]\033[0m %s\n' "$*" >&2; exit 1; }
yaml_quote() {
  local value="${1//\'/\'\'}"
  printf "'%s'" "$value"
}

# ---- sudo -------------------------------------------------------------------
SUDO=""
if [[ "$(id -u)" -ne 0 ]]; then
  command -v sudo >/dev/null 2>&1 || die "Need root or sudo to install packages and k3s."
  SUDO="sudo"
fi

# ---- load .env --------------------------------------------------------------
if [[ -f "$ROOT/.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "$ROOT/.env"
  set +a
  log "Loaded $ROOT/.env"
else
  warn "No .env found. Continuing with defaults; copy .env.example to .env for local overrides."
fi

# ---- config (env or defaults) ----------------------------------------------
K3S_CHANNEL="${K3S_CHANNEL:-v1.34}"
K3S_VERSION="${K3S_VERSION:-}"
INSTALL_K3S="${INSTALL_K3S:-true}"
INSTALL_HELM="${INSTALL_HELM:-true}"

# ---- preflight --------------------------------------------------------------
log "Preflight checks"
[[ -r /etc/os-release ]] && . /etc/os-release || true
[[ "${ID:-}" == "ubuntu" || "${ID_LIKE:-}" == *debian* ]] || \
  warn "This launchable targets Ubuntu/Debian; '${ID:-unknown}' may need manual tweaks."

cores="$(nproc 2>/dev/null || echo '?')"
memgb="$(awk '/MemTotal/ {printf "%.0f", $2/1024/1024}' /proc/meminfo 2>/dev/null || echo '?')"
log "Host: ${cores} vCPU, ${memgb} GB RAM, arch $(uname -m)"

# ---- host deps: Ansible -----------------------------------------------------
if ! command -v ansible-playbook >/dev/null 2>&1; then
  log "Installing Ansible and base packages"
  export DEBIAN_FRONTEND=noninteractive
  $SUDO apt-get update -y
  $SUDO apt-get install -y ansible python3 python3-pip curl git ca-certificates gnupg lsb-release \
    || { warn "apt install of ansible failed; trying pip"; $SUDO python3 -m pip install --upgrade ansible-core; }
else
  log "Ansible already present: $(ansible-playbook --version | head -1)"
fi

# ---- generate inventory (localhost, no SSH) --------------------------------
log "Writing single-node localhost inventory"
mkdir -p "$ANSIBLE_DIR/inventory/group_vars"
cat > "$ANSIBLE_DIR/inventory/hosts.ini" <<'EOF'
# Generated by scripts/setup.sh — single-node, local connection.
[server]
localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python3

[agents]

[k3s_cluster:children]
server
agents
EOF

# ---- generate launchable overrides -----------------------------------------
SECRETS="$ANSIBLE_DIR/inventory/group_vars/secrets.yml"
log "Rendering $SECRETS from .env"
cat > "$SECRETS" <<EOF
# Generated by scripts/setup.sh from .env. Do not commit.
k3s_channel: $(yaml_quote "$K3S_CHANNEL")
k3s_version: $(yaml_quote "$K3S_VERSION")
install_k3s: ${INSTALL_K3S}
install_helm: ${INSTALL_HELM}
EOF
chmod 600 "$SECRETS"

# ---- run the playbook -------------------------------------------------------
log "Running Ansible playbook"
TAGS_ARG=()
[[ -n "${ANSIBLE_TAGS:-}" ]] && TAGS_ARG=(--tags "$ANSIBLE_TAGS")

(
  cd "$ANSIBLE_DIR"
  ansible-playbook site.yml \
    -e @inventory/group_vars/secrets.yml \
    "${TAGS_ARG[@]}"
) || die "Ansible run failed. Fix the error above and re-run ./scripts/setup.sh"

# ---- access summary ---------------------------------------------------------
KUBECONFIG_PATH="/etc/rancher/k3s/k3s.yaml"
NODE_IP="$(hostname -I 2>/dev/null | awk '{print $1}')"

cat <<EOF

$(log "Done. Kubernetes is running on this VM.")
  Cluster
    export KUBECONFIG=${KUBECONFIG_PATH}
    kubectl get nodes
    kubectl get pods -A

  Helm
    helm version

  AI-Q
    Not installed by setup. The tutorial will guide deployment with kubectl and Helm.

  Re-run after editing .env:
    ./scripts/setup.sh

  Node IP:
    ${NODE_IP:-<vm-ip>}
EOF
